### ISSUE TITLE
Add config for other features

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-money-for-kills#2]
I guess there are "hidden features" like announce to the whole server that a group killed a boss.
This should be configurable (not even sure how it is related to the original concept of the module)

**Comment by StygianTheBest** [comment]
Not a hidden feature, and it pertains to the module because it gives money for the kill

As per the module docs:
- Dungeon boss kills are announced to the party
- World boss kills are announced to the world
- Player suicides are announced to the world

**Comment by BarbzYHOOL** [comment]
Also players kills
