### ISSUE TITLE
Config option for suicide announce in group

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-money-for-kills#7]
Very minor suggestion:

`MFK.SuicideAnnounce. = 0` should be renamed to `MFK.Announce.World.Suicide = 0`

And add the option `MFK.Announce.Group.Suicide = 0`

Might even add the guild announce but that should be for another issue

**Comment by Sdyess** [comment]
Just to clarify, you mean that a message would be sent to the entire group for Group.Suicide and one would be sent to an entire guild for Guild.Suicide, etc?

**Comment by BarbzYHOOL** [comment]
yes, i guess it's more useful then sending it to the world lol

i mean in group/raid it can be useful

in guild it can be funny
